log.config:
  logLevel: TEST

db.config:
  names: tradercat
  tradercat:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: '{cipher}AQAskzmH0lMjkeeOVfG8G/SNYfuMoxvlE4EJz1JFZT25EjUsPtHEiHC50rYpgxuWj2qLRYQAPiHx1Ug1xSic6WN+7+uV2RZAHlhQQ3ZNabyyGVmvd/cEadAUwd5/URJuLl1Z1ZIh7GMx58qGGfpOQyogY2bKRLgfJuXe5DoNwl7GChCgxIgCnKwUULHxVS0QOEAbjBG4wz8obn9yzYP+PFKLTFmvGw5vz/tFXBgfhvrGknnrUHf8Cfkl11eSlKhppziL12XPsCkDyT0vKXxRTgKVv2JzvDXUKzx/Xe83eAKaljnMQcJ39QQ16JRa0Aw3eF//g5nE5MaTYMLaIc5tSrWSiiE3NhMDLHz6jjit20TC0iE9shu2kGtfXiUBm9XsByVW49xwcKsbMRV3ZkSrdlb8thvhRUWS9Cs4r03b9aT632hgU2muGZQpjyBTVbCoxvc4l/d6wg2qRr29BlFv9xDGdGdp+NlX8V4iUoosXffHWVhHigakGGmC02roB1kqIiYmpSmRSXaGOjwNA7IQwrYV'
    username: '{cipher}AQB5Zp60Ie87P9frCGjH95guKE4tn0x52DmKFgjIALscHKaF/dN+RBe9x6fH1fU+CSMUx0gff3trwNSEcjPtyJ+c+3izOIrb73kPmmopKW0P9sPlMLOmCm7Exq48eXPZ1VDzt08knGOUWgA36q9pHXvwcv6J2AfHOZ4+09PCVrErvv1+/3GcbfHFkSZhJA0ldzw4wpkphm6r2wj7D2+sVbSzev7LS0rn1MRGL2qDZIktVh9z0x28xALE5HUngnl8T1ah+Dk0RBGrVG0kgqqig0SoWpIfDEKriiDhga17su79tXuLpkZovcnnSR3Q7ypZAO1hvg1HLNrsswBwJG+myVK67LHcML0B60kNwBRuj1Wc1DRappX/bx1AeKkaWkVNdP4='
    password: '{cipher}AQAFJSd83s8S9JX734ioukVP4/q6UhzWRIc0pIIm2MOdQEsTYrYOIWExK7VseJy1fEngc2bLMK7NQLoPLBeoY5/HA1MGdZPudoVIH4KmtgFduT88YJ7Dl8aLfCvQT14J4wrUKrSbtwoCqrqoWJC2UhZWm+JJPf4XMWHUlV+rya3cNQ8bWReQZaw6z0LAfw1Kfb94vya3694FzA6TEOSkKOuQRJqtE6ZSx3I4NdW4eC+V3jd2trQRuCB5uCFqncyjV1Dzntl1EpktbLI5h5iNs6z+5/rbZhKNt6pSLCbZwDTmO8kO0PYyNd4Ub1fcKcJj+xWtMKs7xn8c6XhQ782qy0BJ9ypi1NAAAYBcpcZtxEIvj1gGJa1bnCT6m7XKWgTwIsCyiVS12sPpVA/ztyjOXwKsVM7S5vfaiTle8oTInAB7JA=='
    minimumIdle: 1
    maximumPoolSize: 10

server:
  servlet:
    session:
      timeout: 3600s

spring:
  session:
    redis:
      flush-mode: on_save
      namespace: tradercat
    store-type: redis
  redis:
    host: '{cipher}AQAqQWP5pP5QxH7vqdkp6TgPiK0paPb9KIUS1tRz2Y03Eopgo4uJeYVUrSEebidRgC6byZSRhp8L9pKkOQ4WeR7Mdvyqoldqtjl2qsgD8HfJghovqrwBhPzOY8/TsdPJX24kjIZQ7Pu4vTSYCcnxfOJaUPlJuDnxKoyLpoCX82cURM3fIBN86O0qRvlZBVTWFkRUeDKFE/9INfqIzX73laBaQz8sncWB5UKE5IWkWi/JBPeLU1DB2d8X7+P57oKo0psLtKUflzB6yUNpSRQL9GqEk7Dy9xROAuAySo+hUU438cAb3ldhlhaG/SUoU5PMKuDltQqC5l8OffitNu684C52wswqcN93rYiYXld2fRWHgSCmFXRx6KPmCIPN2z82GFY='
    password: '{cipher}AQBVpVJA+gaMvGlNA18WSqkelHsxg4n1AB7fd4Nvpw6EsPyZKpJ6bGXajCZkMSx6gGpPxEKmoX/S9Iznh6F0TGm0WXs8bOjpCL3CdP1Dp5Y+Ocw06WALtCV/g8XtswYK1I2oXocWCboZ3KtvIKVLArEsfsEAfB7e2t4xWK7uAxE+RSQLpt4qSMoUrJqDK7l+TBUDcO1Eea35yJJqzo0R8zvOzCRdgKhpfIlHKdARdkprq+IaXqG2HNm0D7k2ElypGi1fwAPP068gaCUttJsx/oms0ndyOzYVlC4MVgnJDAyipRIP9fEmnyG3xKp7gaWTPE933ImnwUcyr7D4/PVgRAPB06+7XkomYUw3gWYMNzN1n1umTtCZeB0xwlYGSqP8Wck4XMShJfYO0nV8Q6BtwZMXX5UoyUfPe24tUgZ9KoacBw=='
    database: 0
    port: 8001
    lettuce:
      pool:
        max-active: 10
        min-idle: 2