spring:
  datasource:
    initialization-mode: never
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  thymeleaf:
    enabled: false
  security:
    user:
      name: "${EUREKA_USER}"
      password: "${EUREKA_PASSWORD}"

framework.http:
  maxIdleConnections: 5
  readTimeout: 1s
  connectTimeout: 1s
  writeTimeout: 1s
  keepAliveDuration: 30s
  followRedirects: true
  followSslRedirects: true

http.config:
  maxIdleConnections: 5
  readTimeout: 1s
  connectTimeout: 1s
  writeTimeout: 1s
  keepAliveDuration: 30s
  followRedirects: true
  followSslRedirects: true

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048


ribbon.ServerListRefreshInterval: 5000

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
  threadpool.default.coreSize: 10

mybatis:
  configuration:
    map-underscore-to-camelCase: true
    cache-enabled: false
    use-generated-keys: true
    default-statement-timeout: 10
  mapper-locations: "classpath*:mapper/**/*.xml"

log.config:
  ignoreUrls: /actuator/**
  ignoreSuffixs: .jpg, .jpeg, .gif, .png, .ico, .bmp, .pdf, .doc, .docx, .xls, .xlsx, .ppt, .pptx, .zip, .mp4, .flv, .txt

# jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&readonly=true
