framework.cors:
  allowedOrigins: http://manager.tradercat.net, http://manager.sportsdb.cc
  allowedMethods: GET, POST, OPTIONS
  allowedHeaders: x-requested-with, content-type
  exposedHeaders:
  allowCredentials: true
  maxAge: 3600s
  path: /**